export const profiles = [
  {
    id: '1',
    name: 'Aditya Mohite',
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
    description: 'Frontend Developer Intern',
    address: 'Pune, Maharashtra, India',
    contact: 'aditya@email.com',
  },
  {
    id: '2',
    name: 'Jane Doe',
    image: 'https://randomuser.me/api/portraits/women/21.jpg',
    description: 'UI/UX Designer',
    address: 'Mumbai, Maharashtra, India',
    contact: 'jane@email.com',
  },
  {
    id: '3',
    name: 'Rahul Sharma',
    image: 'https://randomuser.me/api/portraits/men/33.jpg',
    description: 'Backend Developer',
    address: 'Bengaluru, Karnataka, India',
    contact: 'rahul.sharma@email.com',
  },
  {
    id: '4',
    name: 'Sneha Patil',
    image: 'https://randomuser.me/api/portraits/women/45.jpg',
    description: 'Full Stack Developer',
    address: 'Hyderabad, Telangana, India',
    contact: 'sneha.patil@email.com',
  },
  {
    id: '5',
    name: 'Karan Singh',
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    description: 'Data Scientist',
    address: 'Chennai, Tamil Nadu, India',
    contact: 'karan.singh@email.com',
  },
  {
    id: '6',
    name: 'Anjali Gupta',
    image: 'https://randomuser.me/api/portraits/women/66.jpg',
    description: 'Product Manager',
    address: 'Delhi, India',
    contact: 'anjali.gupta@email.com',
  },
  {
    id: '7',
    name: 'Mohit Verma',
    image: 'https://randomuser.me/api/portraits/men/72.jpg',
    description: 'DevOps Engineer',
    address: 'Noida, Uttar Pradesh, India',
    contact: 'mohit.verma@email.com',
  },
  {
    id: '8',
    name: 'Riya Kapoor',
    image: 'https://randomuser.me/api/portraits/women/81.jpg',
    description: 'Quality Assurance Engineer',
    address: 'Ahmedabad, Gujarat, India',
    contact: 'riya.kapoor@email.com',
  },
  {
    id: '9',
    name: 'Vikram Joshi',
    image: 'https://randomuser.me/api/portraits/men/89.jpg',
    description: 'Mobile App Developer',
    address: 'Kochi, Kerala, India',
    contact: 'vikram.joshi@email.com',
  },
  {
    id: '10',
    name: 'Pooja Desai',
    image: 'https://randomuser.me/api/portraits/women/91.jpg',
    description: 'Graphic Designer',
    address: 'Surat, Gujarat, India',
    contact: 'pooja.desai@email.com',
  },
  {
    id: '11',
    name: 'Sanjay Rao',
    image: 'https://randomuser.me/api/portraits/men/92.jpg',
    description: 'Network Engineer',
    address: 'Lucknow, Uttar Pradesh, India',
    contact: 'sanjay.rao@email.com',
  },
  {
    id: '12',
    name: 'Meera Iyer',
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
    description: 'Cybersecurity Analyst',
    address: 'Chandigarh, India',
    contact: 'meera.iyer@email.com',
  },
  {
    id: '13',
    name: 'Deepak Nair',
    image: 'https://randomuser.me/api/portraits/men/26.jpg',
    description: 'Cloud Architect',
    address: 'Bhubaneswar, Odisha, India',
    contact: 'deepak.nair@email.com',
  },
  {
    id: '14',
    name: 'Nisha Menon',
    image: 'https://randomuser.me/api/portraits/women/38.jpg',
    description: 'Business Analyst',
    address: 'Jaipur, Rajasthan, India',
    contact: 'nisha.menon@email.com',
  },
  {
    id: '15',
    name: 'Arjun Patel',
    image: 'https://randomuser.me/api/portraits/men/47.jpg',
    description: 'Software Tester',
    address: 'Indore, Madhya Pradesh, India',
    contact: 'arjun.patel@email.com',
  },
];
